sudo: required
services:
  - docker

before_install:
  - docker build -t hirenshah24/docker-react -f Dockerfile.dev .

# env:
#  - CI=true

 script:
  - docker run hirenshah24/docker-react npm test -- --coverage




